version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sgpi-frontend
    ports:
      - "3004:3004" # Apenas para acesso local; o NGINX deve fazer proxy na produção
    restart: unless-stopped